apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  namespace: adi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: usernode-js
        image: saiteja2502/userprofileretail:latest
        ports:
        - containerPort: 3130
        envFrom:
        - configMapRef:
            name: userprofile-config
        - secretRef:
            name: userprofile-secret





