apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mongodb-config
  namespace: {{ .Values.namespace }}
data:
  MONGO_INITDB_DATABASE: {{ .Values.mongodb.config.MONGO_INITDB_DATABASE | quote }}
