apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.mongodbService.type }}
  ports:
    - port: {{ .Values.mongodbService.port }}
      targetPort: {{ .Values.mongodbService.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.mongodb.app }}
