apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-userprofile-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  SESSION_SECRET: {{ .Values.SESSION_SECRET | quote }}
  EMAIL_USER: {{ .Values.EMAIL_USER | quote }}
  EMAIL_PASS: {{ .Values.EMAIL_PASS | quote }}
