apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  MONGODB_URI: {{ .Values.userprofileMongoUri | quote }}
  PORT: {{ .Values.port | quote }}
